kafka:
  servers:
  - 10.161.229.42:9092
  # - localhost:9092
  group: xts

platform:
  ip: 10.161.229.42
  # ip: localhost
  port: 8000

local:
  # root: C:\RobotTest\workspace\bat_rf
  root: C:\Users\ZIU7WX\Desktop\doc\personal\project\vite-admin-agent\test