kafka:
  servers:
  #  - 10.173.251.55:9092
  #  - 10.173.248.175:9094
   - localhost:9092
  group: xts

platform:
#  ip: 10.173.251.55
  # ip: 10.161.229.42
  ip: localhost
  port: 8000

local:
  # root: C:\RobotTest\workspace\bat_rf
  root: C:\Users\ZIU7WX\Desktop\doc\personal\project\vite-admin-agent\test